### Create user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "userId": -12345,
  "first_name": "Alex"
}


### Find user by tgInitData or create new
GET http://localhost:8080/api/v1/users